### ISSUE TITLE
Dual Leg Mode controls

### ISSUE THREAD

**Issue by tjheideman** [bitfocus/companion-module-polecam-autopod#2]
When operating a Panapod kit in Dual Leg mode, the left and right of the "PTZ" become the second leg controls; while the tilt continues to control the first leg height.
It would be useful to be able to independently control the leg heights within the module (unless the existing module allows this somewhow?).
Any suggestions are welcome!

**Comment by haakonnessjoen** [comment]
In next version being updated now there will be a Dual Leg mode, and a Dual split leg mode, where the last mode would be as you asked for, with left and right controlling the second leg independently.
